// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Prototype.EmployeeService.Implementation.Repository.Pocos
{
	[Alias("Employee")]
    public partial class Employee : IHasId<int> 
    {
        [Alias("EmployeeId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string SSN { get; set; }
        [Required]
        public string EmailAddress { get; set; }
         [References(typeof(Company))]          
        [Required]
        public int CompanyId { get; set; }
    }

}
#pragma warning restore 1591
